language: python
python:
- 2.7
install:
- python setup.py develop
script:
- nosetests -sv --with-xunitmp --with-cov --cov=blumpkin --cov-report term-missing
after_success:
- coverage combine
- coverage report
- coverage xml
- blumpkin coverage coverage.xml blumpkin:90
- find blumpkin -name "*.py" | xargs pep8 --ignore=E711 | tee pep8.out
- blumpkin create-pypi
- blumpkin publish --branch master
env:
  global:
  - PYPI_INDEX=
  - PYPI_USERNAME=balanced-butler
  - secure: X6KAYL6xpcovJAAONRav8B712erQhU1G/loi9CNQM3nvrKfBg4zqx+5nkmktdb13Bgv3HDpzRmVk4222Z9TGXTnChK3O7L2Vb0TwUG1s82GO4Mqsdv97JpxoKlR4HZ4XP9AN7zClieOhSDachG3NSpRLipAW9neLQFF9hS53Ni8=
